repos:
-   repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
    - id: black
      language_version: python3.6

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.4.0
    hooks:
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: check-xml
    -   id: check-added-large-files
    -   id: detect-private-key
    -   id: no-commit-to-branch
        args:
        - --branch=develop
        - --branch=master
        - --branch=fix